### PR TITLE
Fixed the bug related to the dialog box glitch

### PR DESCRIPTION
**Pull request by abansal15**
## Description
Added the height to the dialog box so that it dont glitch while loading

while taking the video i have hard coded the ip address code to hide the ip address but in the pr its not changed.

## Screenshots (if appropriate):

https://github.com/user-attachments/assets/3cc49dcc-1bb8-4d08-a7b1-e3e17fe01995

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by dpgiakatos — CHANGES_REQUESTED** [review]
This solution resolves the problem, but it increases the height of the `UserInfo` component. Please adjust the spinner position instead of changing the component height. Thank you.

**Comment by abansal15** [comment]
@dpgiakatos can you please now review the latest commit i have now added the margin bottom to the spinner now the glitch is fixed .

https://github.com/user-attachments/assets/f8237a08-72d8-484f-9f85-97c65e742668

**Comment by abansal15** [comment]
@dpgiakatos i have changed the sninner bottom margin to 10px and yes its working good with no glitch

**Review by dpgiakatos — APPROVED** [review]
Thanks

**Pull request merged**
