### PR TITLE
Fix: Wrong 'Direct Neighbour' initial status

### LINKED ISSUE #75: Wrong 'Direct Neighbour' initial status
**Describe the bug**
A click on the AS dependency graph shows a detailed table that include a column called 'Direct Neighbour'. These values are wrong if we click too quickly on the graph (e.g. when the page is still loading). The data for this column is fetch by an API call to RIPE stat, if the API call is not complete then all direct neighbor values are displayed as 'x'.

**To Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en-us/networks/AS2497
2. Click as fast as possible on a line of the top graph (AS Dependency)
3. See the all the 'x' values in Direct neighbour. If we click again on the graph (after the page is fully loaded) some of these 'x' become 'v' which is the expected results.

**Expected behavior**
We should show spinning wheels in the direct neighbour column to let the user know that the data is still loading.

**Desktop (please complete the following information):**

- OS: linux
- Browser: brave

### PR DESCRIPTION
**Pull request by anugcodes**
## Description
fixes #75 , 
It do not load the table untill the `asNeighbour` data is loaded. here initially clicking the graph may feel unresponsive also i have added console message stating that the data has not loaded yet.

## How Has This Been Tested?
I have tested the code by running it in the browser and following the steps mentioned in the issue.

## Screenshots (if appropriate):

https://user-images.githubusercontent.com/110781959/233766809-d98b21d0-f847-4bd9-a2ab-167b40f8f6a2.mp4

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

@romain-fontugne sir, is there any further change you want.

### CODE REVIEW

**Comment by thisiskaransgit** [comment]
The issue is still produced, and if we click quickly, on the legend of the Dependency graph then the Chart won't be appearing until click on the Dependent graph.

**Review by thisiskaransgit — COMMENTED** [review]
The issue is still produced, and if we click quickly, on the legend of the Dependency graph then the Chart won't be appearing until click on the Dependent graph.
Kindly look at that.

**Comment by anugcodes** [comment]
> The issue is still produced, and if we click quickly, on the legend of the Dependency graph then the Chart won't be appearing until click on the Dependent graph. Kindly look at that.

@thisiskaransgit  can you please provide more information on this , like any video or image. 
currently if we click click on the legend or on the graph itself , the table will not load until the `AsNeighbour` data has loaded so for now i have added a console message like "the neighbours data not loaded yet". Also there is a issue when we load the table once and then reload the page then the issue in the `Direct Neightbour` column persists. i have found a fix for the reload issue and will add a loader/ or increase the time of existing table loader.

**Comment by anugcodes** [comment]
This is the final result, wrong `Direct Neighbour` initial status is resolved also reloading issue for the Network report page is also resolved. The table is now immedietely show on click on the plot. and the first loading takes a bit longer.


https://user-images.githubusercontent.com/110781959/234021516-d2bd74fe-3957-41d6-ae0b-6951aff5a262.mp4

please review this pr whenever you are free.

**Review by romain-fontugne — APPROVED** [review]
Thanks! it looks good to me

**Pull request merged**
