### PR TITLE
Fixed #395 : Added scrollbar to tables with many records

### LINKED ISSUE #395: Adding scrollbar to tables with many records
There are some tables with many records and a option to choose the number of records to be shown per page. 
By default it is 5-10. But when a large number is chosen, then the records extend up to bottom of the page and this causes problem that the user has to scroll a lot to see some other section of the page. This hurts the user experience. 
So I want to add internal scrollbars to them after a certain number of records.

This can be seen in several places like:
1. AS dependency table in Global section.
image
2. Network dependency table.
image

@romain-fontugne @Aniket762 Please assign this to me. I would like to work on this.
Thanks!

### PR DESCRIPTION
**Pull request by kkartik07**
Fixes #395 
I have added scrollbars to various tables where there are many records.
There are some tables with many records and a option to choose the number of records to be shown per page.
By default it is 5-10. But when a large number is chosen, then the records extend up to bottom of the page and this causes problem that the user has to scroll a lot to see some other section of the page.

The scrollbar appears only when the table height crosses a certain max-height, otherwise it is not visible.

For example:
When less records are there:
image

When records per page is increased to 10:
image

@romain-fontugne @Aniket762 Please review the changes and merge it.
Thank you.

### CODE REVIEW

**Comment by thisiskaransgit** [comment]
Since you are repeating the same style in multiple components, the suggested approach would be to move the styles in the globe styles file such that it can be accessed easily. It will reduce code redundancy, which is important.

And this is not the most optimized way of implementing it, try either `scrollbar-width` or something else.

**Comment by kkartik07** [comment]
There is no related global style sheet, so I will have to create a new global style sheet file for tables.

**Comment by kkartik07** [comment]
@thisiskaransgit can you give some more details of how can we optimize it, as I think it wont effect much.
Please suggest improvements to optimise it

**Comment by kkartik07** [comment]
@romain-fontugne Should I also change the style of the main scrollbar for website similar to others, making it look more think and modern? 
It will look like this :
image

**Pull request closed without merging**
