### PR TITLE
300/added hyperlink to the organization's logos in the welcome back section.

### PR DESCRIPTION
**Pull request by Arunjagan12**
## Description
the logos present in the welcome back section which is situated in the home page has hovering property.But,when clicked it doesn't redirect to any webpage.

## Motivation and Context
I have added hyperlink property to the organization's logos to redirect to their respective websites.

## How Has This Been Tested?
this has been tested by clicking on those logos which redirected to the respective organization's website.A changes made can be seen in the below video.

https://user-images.githubusercontent.com/96646536/222642520-74350828-89d9-4c46-9c7b-fc097413a417.mp4

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by ConnectBhawna** [comment]
@Arunjagan12 can you make it something like that. When we click on logo it opens in new tab instead of same one.
According to me that looks more good. Just add _blank attribute into it. It works

**Comment by Arunjagan12** [comment]
Sure @ConnectBhawna , I taught of that first, but I have come across some issues before in this website that suggested to open webpages same tab itself. So I haven't considered it.

**Comment by ConnectBhawna** [comment]
Ohh let's wait what @romain-fontugne sir say on this.
Than make the changes accordingly.
Good work @Arunjagan12 Keep going :)

**Comment by romain-fontugne** [comment]
yes, I agree external links should open in a new tab!

**Comment by Arunjagan12** [comment]
I have made those changes as well @romain-fontugne sir

**Review by romain-fontugne — APPROVED** [review]

**Comment by romain-fontugne** [comment]
Looks good to me, thanks for your contribution!

**Comment by ConnectBhawna** [comment]
Great work @Arunjagan12 :)

**Pull request merged**
