### PR TITLE
Updated Twitter Old twitter Logo 

### PR DESCRIPTION
**Pull request by MAVRICK-1**
## Description
Updated Old twitter
fixed the issue of #667 

## Screenshots (if appropriate):

Screenshot 2023-12-15 184046

## Types of changes
IHR TWEETS Logo updated

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the code style of this project.
@romain-fontugne @mohamedawnallah review

### CODE REVIEW

**Comment by mohamedawnallah** [comment]
Consider placing the image in the [src/assets/imgs](https://github.com/InternetHealthReport/ihr-website/tree/master/src/assets/imgs) directory rather than downloading it from the data source every time the page is loaded, thereby avoiding additional dependency and latency.

**Comment by MAVRICK-1** [comment]
Okay on it

**Comment by MAVRICK-1** [comment]
@mohamedawnallah now its okay?

**Comment by mohamedawnallah** [comment]
LGTM! Thanks

**Comment by RickDeb2004** [comment]
> @mohamedawnallah now its okay?

@MAVRICK-1 @mohamedawnallah don't you think direct use of image can affect the website for long term perspective....
as storing images in Cloudinary  would be better for scalability purpose.

**Comment by MAVRICK-1** [comment]
@RickDeb2004 I didn't use any direct image from the website all my images are stored in src/assets/img

**Comment by mohamedawnallah** [comment]
@RickDeb2004 I don't think adding `116 KB` images (`twitter.png` + `x_footer.png` combined) to `src/assets/imgs` would cause a scalability problem.

**Comment by dpgiakatos** [comment]
closed by [#669](https://github.com/InternetHealthReport/ihr-website/pull/669)

**Pull request closed without merging**
