### PR TITLE
Added hover effect. Issue #593

### PR DESCRIPTION
**Pull request by 0xAnon0602**
## Description

Added hover effect on navbar instead of clicking to show the submenu

Solves the issue #593  

## Screenshots (if appropriate):

https://github.com/InternetHealthReport/ihr-website/assets/71931823/125e4aed-7b2b-4253-ad5b-6576f7d87643

### CODE REVIEW

**Comment by romain-fontugne** [comment]
Thanks, but it would be nice if the menu closes when we click on a link. 

For example, if now I hover reports and click on 'network reports' it goes to the appropriate page but the menu closes and reopen right away

**Comment by 0xAnon0602** [comment]
Got it 
Will fix this issue

**Comment by 0xAnon0602** [comment]
@romain-fontugne The issue has been fixed with new commit

**Comment by 0xAnon0602** [comment]
@romain-fontugne Does this require any other changes?

**Review by romain-fontugne — APPROVED** [review]
looks good, thanks!

**Pull request merged**
