### PR TITLE
Fixed the Issue of showing Correct Message

### PR DESCRIPTION
**Pull request by ConnectBhawna**
## Description
Here, I solved the issue #5 opened by @romain-fontugne sir. It says for network with no AS (Autonomous System) dependency, there are two possible scenarios that can be considered.

The first possibility is that the network is super distributed and has no dependency on any other AS in the network. In other words, this network operates completely independently and does not rely on any other networks to function properly. An example of such a network could be Google, which has a large number of data centers spread across the globe, making it relatively independent of other networks.

The second possibility is that the network does not announce any IP (Internet Protocol) space. This means that the network exists but does not announce its presence or availability on the internet. This could be for various reasons such as security concerns, limited resources, or a deliberate decision not to participate in the global routing system.

To distinguish between these two cases, one can use results from the global graph, which is a graph representation of the internet's interconnections between networks. In the case of a super distributed network, the global graph would show that the network has connections to many other networks, but it does not rely on any one network for its operation. On the other hand, in the case of a network that does not announce its IP space, the global graph would not show any connections to or from that network.

Printing corresponding messages for each case could help clarify the situation. For example, if the network is super distributed, a message like "This network operates independently and has no AS dependencies" could be printed. In the case of a network that does not announce its IP space, a message like "This network exists but does not announce its presence on the internet" could be printed.

## Motivation and Context
The motivation behind the problem is to identify and understand the characteristics of networks that do not have any AS dependency or do not announce their IP space. This is important because it can provide insights into the way networks are designed and operated, and how they interact with each other.

For example, identifying super distributed networks that operate independently of other networks can help in designing more resilient and fault-tolerant networks. On the other hand, understanding why some networks do not announce their IP space can help in improving the security and privacy of these networks.

The context of the problem is within the field of network engineering and network topology analysis. The global graph, which is a graph representation of the internet's interconnections between networks, is a key tool in this field. By analyzing the connections and dependencies between networks in the global graph, network engineers can identify patterns and characteristics that can help in designing and optimizing networks.

## How Has This Been Tested?

To test the phenomenon you can refer to the video demonstration. The video shows that if the graph has no network dependency2, then in this case it  shows a message "No network dependency", but if the  graph is empty because we have no data for the selected network , in this case we show a message like "Network unreachable". This is demonstrated in the video.
[issue_5.webm](https://user-images.githubusercontent.com/81790585/225401190-6fa47b2e-592e-4457-a174-72591d1d1ea0.webm)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by romain-fontugne** [comment]
Thanks but it seemed to have broke the upper graph. Now when I go to AS2497, I don't see the upper graph appearing?

**Comment by ConnectBhawna** [comment]
Okk sir let me fix this out :)

**Comment by ConnectBhawna** [comment]
@romain-fontugne sir fixed this , just did one mistake from my side.
Now it is running good, You can see this in this video.
Link : [bug_fixed.webm](https://user-images.githubusercontent.com/81790585/227000768-e6fc5e66-8db1-42e9-9f69-a7da781dea52.webm)


Let me know if this PR needs further changes as well.
Thanks & Regards
Bhawna

**Review by romain-fontugne — APPROVED** [review]

**Comment by romain-fontugne** [comment]
Thanks!

**Pull request merged**
