### PR TITLE
Exploratory Dashboard UI improvisation 

### PR DESCRIPTION
**Pull request by Yh010**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=TdEBC62)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Aniket762** [comment]
Hi @romain-fontugne, Yash and I had met recently in which I told your vision about how the dashboard's UI should look like. And he was working on it accordingly.

Do you mind reopening the issue?

**Comment by romain-fontugne** [comment]
sure

**Comment by kkartik07** [comment]
Can I too work on this issue along with @Yh010 or you can discuss how you want the dashboard to be, so that I can work on it in some way

**Comment by dpgiakatos** [comment]
closed by [#634](https://github.com/InternetHealthReport/ihr-website/pull/634) and [#669](https://github.com/InternetHealthReport/ihr-website/pull/669)

**Pull request closed without merging**
