### PR TITLE
Minor styling fix on traceroute monitor

### PR DESCRIPTION
**Pull request by TasosY2K**
## Description

Centered labels for RTT and ASN mode 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dpgiakatos** [comment]
Hi. Could you please run `npm run lint`?

**Comment by TasosY2K** [comment]
I tried to but im getting this error.
```
> ihr-website@1.4.0 lint
> eslint . --ext .vue,.js,.jsx,.cjs,.mjs --fix --ignore-path .gitignore

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.

```

**Comment by dpgiakatos** [comment]
It's ok then. I will fix this error.

**Review by dpgiakatos — APPROVED** [review]
Thanks!

**Pull request merged**
