### PR TITLE
Feature/Global Report V2

### PR DESCRIPTION
**Pull request by mohamedawnallah**
## Description

This pull request addresses the following:
1. [Empowered users to filter the bottom table with precision by selecting criteria such as country, ASN, time, severity, and IP address family.](https://github.com/orgs/InternetHealthReport/projects/10?pane=issue&itemId=37661985)
2. [Identified and extracted hegemony alarms exhibiting a substantial deviation of less than -20, ensuring a focus on the most critical anomalies.](https://github.com/orgs/InternetHealthReport/projects/10?pane=issue&itemId=38673432)
3. [Revamped the interface by renaming 'reset granularity' to 'show all countries’ and moving the buttons next to the data vizs for greater clarity and convenience.](https://github.com/orgs/InternetHealthReport/projects/10?pane=issue&itemId=37675256)
4. [Introduced versatile options for switching between originasn and asn for AS hegemony alarms, start and endpoint for network delay alarms, and attacker and victim for GRIP Alarms.](https://github.com/orgs/InternetHealthReport/projects/10?pane=issue&itemId=37684920)
5. [Enhanced control by enabling the filtering of alarms by IP address families 4 and 6.](https://github.com/orgs/InternetHealthReport/projects/10?pane=issue&itemId=38673321)
6. [Expanded our system by adding disco alarms to the list of IHR alarms.](https://github.com/orgs/InternetHealthReport/projects/10?pane=issue&itemId=38673277)
7. [Tailored the dashboard to offer the ability to select a default alarm type(s), with hegemony as the new default.](https://github.com/orgs/InternetHealthReport/projects/10?pane=issue&itemId=38673908)
8. [Fostered a seamless and engaging experience by integrating full interactivity among data visualizations, including the WorldMap, TreeMap, TimeSeries, and Table Data Visualizations.](https://github.com/orgs/InternetHealthReport/projects/10?pane=issue&itemId=37675301)
9. [Enhanced performance by accelerating the loading of the dashboard, bypassing network requests to retrieve AS names and country information from IHR networks and instead utilizing RIPE's asnames.txt file.](https://github.com/orgs/InternetHealthReport/discussions/14)
10. [Introduced comprehensive overviews for Neighbor Dependency in Hegemony, Round-Trip Time in Network Delay, Latency Overview in Network Delay, and AS and Country Internet in IODA, along with a reusable aggregated overview spanning IHR, GRIP, and IODA data sources.](https://github.com/orgs/InternetHealthReport/discussions/20)
11. [Identified and logged dynamically missing autonomous systems not found in the asnames.txt file, making it a potentially valuable "good first issue" for contributors.](https://github.com/InternetHealthReport/ihr-website/assets/69568555/b5771cbc-62b7-4f3d-ac76-03ebc4938b27)
12. Addressed critical bugs related to the ASInterdependenciesChart.vue component, ensuring seamless data handling. #632 #633
13. Welcomed Merit Network Telescope as a new IODA Alarm Type and integrated Google Transparency Report [Google Search] into AS and Country Internet IODA Overview.
14. Enhanced the user experience with custom dynamic metrics in data visualization titles, adapting dynamically to the user's journey through the dashboard.
15. Updated documentation for streamlined processes and enhanced user experience, including alarm type and data source addition, default alarm type selection, group by key customization, and text content modification in filters and data visualizations, facilitating efficient system configuration and text personalization.

## How Has This Been Tested?
Rigorously validated with an extensive suite of 133 comprehensive test cases.

## Recordings

https://github.com/InternetHealthReport/ihr-website/assets/69568555/8b8d000d-2dec-4a44-a1a2-f25e63a0cc32

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by romain-fontugne** [comment]
🤩
This is great, I think we can cleanup a bit the page now, for example the date/calendar a the top is not needed anymore. Also maybe to make the page faster we could show only one day of data?

**Comment by mohamedawnallah** [comment]
Thanks for the feedback! I think so regards showing only one day of data that would be a lot faster especially incase of Hegemony Alarms where we get >20 and <-20 alarms. I have implemented the suggested changes. Please check them out and let me know!

global-report-v2-updated

**Comment by romain-fontugne** [comment]
So now I'm not sure I use that correctly. Let's say I want to look at results a few days ago. I try to set the dates in the time filter fields and click on apply but it doesn't work?

These fields are only for filtering results? If so then we might want to put back the date at the top of the page

**Comment by mohamedawnallah** [comment]
@romain-fontugne Yes those time filters for filtering the results only. In the new commits I’ve done the following:
- Returned the date time picker and make interactive with other data visualization.
- Solved the Redundant Navigation error in the global report page.
- Made the IHR Network Requests Asynchronous. In the 3 day report I made it synchronous so not to put the IHR server down now In our one day range report that would be fine .

PS:
I will open good first issues after this PR for other pages where Redundant Navigation Error happens and how to solve it.

**Comment by romain-fontugne** [comment]
Looks great, thanks!

**Comment by romain-fontugne** [comment]
ah wait, it looks like the AS hegemony graphs now throw an error when we click on it?

**Comment by mohamedawnallah** [comment]
Thanks for the catch! Addressed in this PR #642

**Comment by mohamedawnallah** [comment]
@romain-fontugne we may also need to change the ? icon info for Network Disconnection Alarms in the filters table. I made placeholder text “Network Disconnection Alarms"

**Comment by romain-fontugne** [comment]
Ok, thanks! I'll take care of this

**Pull request merged**
