### PR TITLE
added gsoc logo in the special thanks section

### PR DESCRIPTION
**Pull request by Arunjagan12**
## Description
added gsoc logo in the home page

## Screenshots (if appropriate):
Screenshot (33)

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by romain-fontugne** [comment]
Thanks, can you replace it with the logo that says 'Google summer of code':
https://developers.google.com/open-source/gsoc/resources/marketing

I'm not sure people would just recognize the logo

**Comment by Arunjagan12** [comment]
Sure sir

**Comment by Arunjagan12** [comment]
Screenshot (34)

I've updated the logo sir.

**Comment by Aniket762** [comment]
Thanks @Arunjagan12, looks good to me. Merging the PR rightaway

**Pull request merged**
