### PR TITLE
Fix GRIP CORS problem

### PR DESCRIPTION
**Pull request by romain-fontugne**
The global report had a problem to show GRIP alarms because of CORS checks.
The code is now using a proxy server hosted by IHR to fetch GRIP and IODA data.

This code also raise the default minimum suspicion value for GRIP, in order to focus only on important alarms.

### CODE REVIEW

**Comment by mohamedawnallah** [comment]
This causes the regression to severities filters as changing from `normal` to `medium`  in `AggregatedAlarmsDataModel` requires changing it in the `AggregatedAlarmsFilters` UI component to auto initialize it when the user selects `Medium` for example:
```html
    <!---- the other filters !---->
        <label>    
            <input type="checkbox" v-model="severities.normal" :disabled="loadingVal"> Normal
        </label>
     <!---- the other filters !---->
```
To:
```html
    <!---- the other filters !---->
        <label>    
            <input type="checkbox" v-model="severities.medium" :disabled="loadingVal"> Medium
        </label>
     <!---- the other filters !---->
```

I created PR #571 with the primary purpose of refactoring the AggregatedAlarmsController code, primarily focusing on severities. Additionally, I addressed a regression issue, simplifying the changes into a single PR.

**Comment by romain-fontugne** [comment]
ah sorry! thanks for the fix!

**Comment by mohamedawnallah** [comment]
@romain-fontugne This PR is related to this as well #572

**Comment by romain-fontugne** [comment]
ok, thanks! merged

**Pull request merged**
