### PR TITLE
Migrating from Vue.js 2 to Vue.js 3

### PR DESCRIPTION
**Pull request by dpgiakatos**
## Description

This pull request aims to upgrade the project from Vue.js 2 to Vue.js 3, bringing several enhancements, performance improvements, and new features. The migration to Vue.js 3 offers a more modern and maintainable codebase, aligning with the latest advancements in the Vue ecosystem.

### Motivation:
- **Vue.js Version Upgrade:** Upgraded Vue.js from version 2 to version 3.
- **Composition API Integration:** Leveraged the Composition API for cleaner and more modular component logic.
- **Improved Reactivity:** Vue.js 3 introduces a more efficient reactivity system, resulting in better performance and a smoother user experience.
- **Optimized Bundle Size:** The new version includes tree-shaking improvements, leading to a reduced bundle size and faster loading times.

### Context:
1. **Performance Boost:** Vue.js 3 comes with optimized rendering and reactivity mechanisms, leading to faster component updates and improved overall performance.
2. **Maintainability:** The Composition API encourages better organization of component logic, making the codebase more maintainable and readable.
3. **Future-Proofing:** By upgrading to the latest version of Vue.js, we ensure compatibility with future updates and take advantage of ongoing improvements and new features.
4. **Community Support:** Vue.js 3 has gained widespread adoption, resulting in a vibrant and active community. This means better community support, increased availability of third-party libraries, and a wealth of resources for developers.

---

This pull request addresses [Issue #469](https://github.com/InternetHealthReport/ihr-website/issues/469). It is a significant step toward keeping our project technologically current and ensuring a positive development experience for our contributors. Feedback from the community on the migration process is highly encouraged.

Please review and provide any comments or suggestions. Thank you for your attention to this important update.

#### Description:
One specific enhancement opportunity is to replace the list section on the Global Report V1 page with the tabs section from the Global Report V2 page. Additionally, the Global Report V2 page should utilize the Quasar library for the components.

#### Steps:
1. Navigate to the Global Report V1 page.
2. Identify the list section.
3. Replace the list section with the tabs section from the Global Report V2 page.
4. Ensure that the Global Report V2 page is using components from the Quasar library.

#### Acceptance Criteria:
- The Global Report V1 page should display the tabs section from the Global Report V2 page.
- Quasar components should be integrated into the Global Report V2 page.

#### Description:
The website currently uses the i18n library for internationalization. However, not all pages have been converted to the i18n standard. Additionally, the existing version has two translation files (en, jp), but the text has not been translated. There is a need to convert all pages to the i18n standard and create a new, more convenient architecture for the translation files.

#### Steps:
1. Review each page of the website.
2. Identify pages that have not been converted to the i18n standard.
3. Evaluate the existing translation files (en, jp) and assess the need for translations.
4. Propose and implement a new architecture for translation files.

#### Acceptance Criteria:
- All pages should be converted to the i18n standard.
- Translation files should be organized in a new, more convenient architecture.

#### Description:
The website currently uses one cookie for lazy translation. To enhance user experience and comply with GDPR regulations in the EU, a new feature is needed to prompt users about their preferences regarding cookies. Additionally, the new feature should utilize the Quasar library for the components.

#### Steps:
1. Explore the website and identify the current cookie usage for lazy translation.
2. Propose and implement a new feature to ask users if they want to use cookies.
3. Ensure that the new feature aligns with GDPR regulations.
4. Ensure that the new feature is using components from the Quasar library.

#### Acceptance Criteria:
- Users should be prompted about their cookie preferences.
- The new feature should comply with GDPR regulations.

---

Feel free to customize the details and steps based on your specific project needs. This set of issues provides a starting point for addressing the identified concerns during the Vue.js 3 migration.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mohamedawnallah** [comment]
Thanks, @dpgiakatos, for spearheading the Vue.js 3 migration. I noticed that the PR is based on commit d4868fc4a5d1abc832c0672d137b289ffeb98842, currently in production at [ihr.iijlab.net](https://ihr.iijlab.net/ihr/en-us), just before the Global Report V2 Feature. While I appreciate the effort, there are several points in the PR changes I disagree with:

1. **Separation of UI Changes and Naming Conventions:**
- It is inconsistent with the commit you checked it out from which is currently in production that means no UI or naming convention changes should be done for the sake of separation of concerns, especially for the main Migration purpose of this PR.
- It becomes hard to know how `Vue.js 3` differs from `Vue.js 2` in the PR.
- It becomes hard for the contributors who would build upon this commit especially for the commit f694d4baef18d385b8ff6eda32d94a3084068a18 which is related to the Global Report V2 which is in `Vue.js 2`
- It creates a different user experience not necessarily better.

The Global Report V1 that’s currently in production https://ihr.iijlab.net/ihr/en-us/global_report:
Screenshot 2023-12-15 at 3 55 15 AM

The Global Report V1 that’s addressed in this Migration PR:
Screenshot 2023-12-15 at 3 55 47 AM   

   - Notably, the migration PR showcases significant UI changes, inconsistencies between Global Report V2 and V1, and unexpected behaviors. I've highlighted some of these in an image, though not exhaustive. Apologies for the cluttered image, but it aimed to capture all changes in one place.

   Image Overview - Identified UI Changes, Inconsistencies, and Unexpected Behavior

2. **Maintaining Code Structure and File Deletion:**
We should maintain the same code structure and (avoiding deleting files that the logic/tests depend on) as in the [main branch in ihr-website](https://github.com/InternetHealthReport/ihr-website/) this is for multiple potential reasons as well:
- It creates too many merge conflicts
- It creates too many changes in the git tree e.g in this case it is `213` files changed it becomes harder for the reviewers
- It becomes harder to review
- It may arise bugs as deleting files changes the logic that depends on those files

3. **Missing Test Files for Data Models and Husky Files for Git Hooks:**
   - Notably absent are the test files for Data Models and husky files for git hooks, which will result in a failed CI Test pipeline.

In full transparency, I haven't reviewed the entire PR due to its extensive scope. However, these highlighted points indicate that merging this branch into the `main` branch directly wouldn't be advisable without addressing these crucial issues. There's considerable work needed before merging.

**Comment by MAVRICK-1** [comment]
Issue 2)Internationalization (i18n) Standardization and Architecture Refinement has been done in italian language .

https://github.com/InternetHealthReport/ihr-website/assets/146999057/fae7615b-7043-4e07-856b-94ba4f74748e

**Comment by romain-fontugne** [comment]
@mohamedawnallah thanks, those are good comments. Yes there is changes that are not inline with the previous global report v1 but instead of spending time on reverting these changes maybe we should concentrate our efforts on migrating the global report v2 to vue3?
 
For this PR, I need to extensively test it to make sure that all functions (apart from the global report) are still working. And I wish we could merge it quickly because other contributors are waiting for this PR to add new code.

**Comment by romain-fontugne** [comment]
Here are a my first impressions with the new version. It does feel faster than before :)
I'm glad we got that much done already. Just a few things that bother me:
1 - I get a strange `[object object]` text appearing after searching for an AS in the top left search bar:
image
2 - I think we should add the redirection from / and /ihr to the homepage
3 - the first time I run it, I got an error message ('impossible to load the style sheet')? but I cannot reproduce that
4 - the h3 text seems a bit too big compare to the rest (this could be related to the style sheet error?)
5 - there is a huge white space on top of the BGPlay widget in the network report
6 - we lost our blinking logo when the app is loading?

**Comment by MAVRICK-1** [comment]
> space

@romain-fontugne sir , I didn't encounter the 1st problem but this new version is really fast smoother than previous one but there are few UI problem which can be rectify.But overall this version is good .

**Comment by mohamedawnallah** [comment]
> 1 - I get a strange `[object object]` text appearing after searching for an AS in the top left search bar.

I confirm that this issue exists:
Object Object Issue in Network Report

**Comment by dpgiakatos** [comment]
Hello, I have completed the migration of the global report v2 to the new proposed architecture. Additionally, the UI can be further improved, but we can address that after the merging process.

**Comment by mohamedawnallah** [comment]
A big shoutout to @dpgiakatos for the amazing work! It's a substantial improvement 🤩. While reviewing the ihr-website, most things look great, except for a few bugs on the global report page. I'm eager to handle these in a PR.

Intrigued, I ran a bundle size benchmark using Webpack Bundle Analyzer between `vue.js 2` and `vue.js 3` versions. The results are striking: with vue.js 2, the bundle size hits `~41 MB`, whereas with vue.js 3, it's only `~9MB` — marking a massive `78%` reduction!

Before merging, @dpgiakatos, there are some merge conflicts to resolve.

@romain-fontugne, I believe it's fine to merge this into our `master` branch. However, let's hold off on pushing this version to production until I've submitted a PR addressing some bugs, UI changes (like the Date Time Filter for the alarms), along with the test and linting files. I'll have that ready very soon.

**Comment by romain-fontugne** [comment]
Thanks! I've tried it and I agree with @mohamedawnallah this is a good version. Some more polishing can be done after the merge. Because of the conflicts it looks like I cannot merge it on the web interface. I'll try to resolve the conflicts and push it to the master branch!

Thanks a lot for all the efforts.

**Comment by romain-fontugne** [comment]
merged! thanks again!

**Pull request merged**
