### PR TITLE
Bug#375 Fixed button styling and moved toolbox section to top

### PR DESCRIPTION
**Pull request by kkartik07**
Button styling changed and made more consistent with the Add button in covid19 section.
Before:
image
After:
image

Also I have moved the toolbox section to the top for easy visibility :
Before:
image
After:
image

Thanks!

### CODE REVIEW

**Review by romain-fontugne — APPROVED** [review]
Thanks

**Comment by romain-fontugne** [comment]
oh, somehow you have a conflict with the master branch, can you fix this?

**Comment by kkartik07** [comment]
> oh, somehow you have a conflict with the master branch, can you fix this?

Ya, sure!

**Review by romain-fontugne — APPROVED** [review]
looks good, thanks

**Pull request merged**
