### PR TITLE
updated global report page to be responsive for smaller screens

### PR DESCRIPTION
**Pull request by Avi-88**
Fixes the issue #263 

## Description

- Updated numeric metrics to be displayed in cards and used css grid for making them responsive.
- Updated table headers to be responsive using flexbox

## Motivation and Context

Enhancement is user experience on smaller screens. 

## How Has This Been Tested?

Tested using browser dev tools for different sized screens on Brave and chrome

## Screenshots (if appropriate):

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by romain-fontugne** [comment]
Thanks, for this contribution. I wonder why the graph/tables now have a border (IHR_charts-body) ?
Is it possible to just remove the border?

**Comment by Avi-88** [comment]
> Thanks, for this contribution. I wonder why the graph/tables now have a border (IHR_charts-body) ? Is it possible to just remove the border?

Oh I think I must've put it to enhance the box shadow , I'll check again and see what can be done. Also I'm looking into making the map responsive too , should I make a different PR for it or just push it to this one ? It might take some time for me to figure it out that's why I asked, thanks

**Comment by romain-fontugne** [comment]
Thanks, that'd be nice to also have the map responsive. You can push both in this PR

**Comment by Avi-88** [comment]
Regarding the border for graphs/tables , I've removed it but I wanted to hear your opinion on giving it a box shadow and border radius in order to create some seperation and to match the stat cards like this 

image

or should I keep it as it is now 

image

**Comment by romain-fontugne** [comment]
Yes the shadow looks good to me. But I wish it also include the header (AS dependency text with the right button) if possible?

**Comment by Avi-88** [comment]
> Yes the shadow looks good to me. But I wish it also include the header (AS dependency text with the right button) if possible?

Yeah sure, if we do it that way it would look something like this 

image

**Comment by romain-fontugne** [comment]
That's great, thanks!

**Comment by romain-fontugne** [comment]
@Avi-88 sorry I didn't intend to merge right away, please make a new PR with the latest version

**Comment by Avi-88** [comment]
> @Avi-88 sorry I didn't intend to merge right away, please make a new PR with the latest version

No worries , I'll make a new one asap

**Pull request merged**
