### PR TITLE
Improved the footer layout 

### LINKED ISSUE #308: Footer enhancement
Screenshot_2023-03-05-09-04-53-856-edit_com brave browser

I think the footer could be more interactive it's not looking that much good. 
What do you think? @romain-fontugne

### PR DESCRIPTION
**Pull request by anugcodes**
## Description
improved the website footer layout to be responsive.

## Motivation and Context
Closes #308 

## How Has This Been Tested?
I have tested it in my local machine.
the footer feels responsive in desktop, tablet and mobile devices.

## Screenshots (if appropriate):
This is how it looks in 
- desktop view
desktop_view

- tablet view
tablet_view

- mobile view
mobile_view

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

@romain-fontugne sir, please let me know if the changes made are satisfactory and mention any further changes that can be made.

### CODE REVIEW

**Comment by J0SAL** [comment]
Hey @anugcodes , just some suggestions, feel free to ignore them.
1. The syntax you have used to link an issue to PR is incorrect, you can refer to the following guide: [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
2. Try going through [contributing guidelines for IHR](https://github.com/InternetHealthReport/ihr-website/blob/master/CONTRIBUTING.md), it details naming conventions for the title of PR, commits messages, etc.
3. Also I noticed that you sent a PR via the master branch of your forked repo, please try to use a different branch for each PR.

**Comment by anugcodes** [comment]
> Hey @anugcodes , just some suggestions, feel free to ignore them.
> 
>     1. The syntax you have used to link an issue to PR is incorrect, you can refer to the following guide: [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
> 
>     2. Try going through [contributing guidelines for IHR](https://github.com/InternetHealthReport/ihr-website/blob/master/CONTRIBUTING.md), it details naming conventions for the title of PR, commits messages, etc.
> 
>     3. Also I noticed that you sent a PR via the master branch of your forked repo, please try to use a different branch for each PR.

hey @J0SAL , thanks for the suggestion i will keep them in mind. and will do the needful right away.

**Comment by romain-fontugne** [comment]
Thanks, can you please Capitalize the first letter of each entry in the menu? you should do that using CSS

**Comment by anugcodes** [comment]
> Thanks, can you please Capitalize the first letter of each entry in the menu? you should do that using CSS

done @romain-fontugne  sir , please take a look

capitalize_first_letter

**Review by romain-fontugne — APPROVED** [review]
thanks!

**Pull request merged**
