### PR TITLE
BugFix/Handle null pointer when the as hegemony graph clicked in the network report

### PR DESCRIPTION
**Pull request by mohamedawnallah**
## Description
Fixes:  Error in v-on handler: "TypeError: clickData.points is undefined"

## Motivation and Context
https://github.com/InternetHealthReport/ihr-website/pull/634#issuecomment-1831894335

## Recordings

https://github.com/InternetHealthReport/ihr-website/assets/69568555/8ee6df6b-9e8a-4519-bcf9-bf0ba2dbd9b0

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by romain-fontugne** [comment]
hmmm, I see a lot more breaking things now:
1. Why is the graph now reloading everytime we click on it?
2. It seems that the 'Direct Neighbor' column in the table is not updated

**Comment by mohamedawnallah** [comment]
Let me investigate this further and will let you know!

**Comment by mohamedawnallah** [comment]
Okay the main issue is that I used the [interval computed property](https://github.com/InternetHealthReport/ihr-website/blob/f694d4baef18d385b8ff6eda32d94a3084068a18/src/views/mixin/reportMixin.vue#L91) in the `ReportMixin.vue` which under the hood listens for the changes of query date field. This works well for getting alarms from X time to Y time but this cause re-rendering of the data vizs when clicked because the dates is updated in the query address.


https://github.com/InternetHealthReport/ihr-website/assets/69568555/559a0c46-34c4-41fb-a212-8f501cc81727


I handled both the cases in the new commits. Thanks again for letting me know about this issue

**Comment by mohamedawnallah** [comment]
@romain-fontugne Could you please elaborate more on this: 
"It seems that the 'Direct Neighbor' column in the table is not updated"

**Comment by romain-fontugne** [comment]
> @romain-fontugne Could you please elaborate more on this: "It seems that the 'Direct Neighbor' column in the table is not updated"

From your last screenshot it seems to work as expected. Thanks!

**Pull request merged**
