### PR TITLE
Updated Translation of local language (ITALIAN) in the  @Website

### PR DESCRIPTION
**Pull request by MAVRICK-1**
<h1 # @>Updated Translation of local language (ITALIAN) in the  @Website<h1>

## Description
<h1>Added the instances of Local language Selector for (ITALIAN) Language for Translation of website .</h1>
<h2>updated the instance of </h2> 

1)genericErrors
2)header
3)footer
4)searchBar
5)GlobalReport
6)Networks
7)charts
8)SigIn
9)Account Activation
10)resetPassword
11)personalPage
12)forms
13)user
<h1>Updated the Documentation into italian <h1>
<h2>Updated parts of Documentation Page : </h2>

1)Section
2)FAQ
3)ack
4)Gloabl reports
5)network Reports
3)country report
5)As dependency
4)Country As Dependency
5)Prefix As Dependency
6)Net delay
7)Delay Forward
8)Disco
9)Api
10)Python Library
11)Dumps
12)Data Policy

 It can be added in the website using  Vue-I18n plug in
documentation of  Vue I18n : ### https://vue-i18n.intlify.dev/guide/
## Motivation and Context

Designing a web application so it can be adapted and localized to different cultures , regions , and language
wanted to add more in the future.
;

## Types of changes

- [ ] New feature (non-breaking change which adds functionality
<br>
<h2>Wanted work on the selctor after migration to vite/vue3 </h2>

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
#664

**Comment by MAVRICK-1** [comment]
@romain-fontugne @mohamedawnallah just view it once

**Comment by romain-fontugne** [comment]
sorry we won't merge until we migrated to vue3 (please join the slack for the announcement)

**Comment by MAVRICK-1** [comment]
Sir , can I work on German and French documention utill the migration is full done.

**Comment by romain-fontugne** [comment]
sure! thanks

**Comment by dpgiakatos** [comment]
The application has been upgraded to Vue 3.js with a new file structure. This pull request is identical to the one at #701, which addresses the same issue in the upgraded code. I am closing this duplicate pull request.

**Pull request closed without merging**
