### PR TITLE
Search bar changes to include Prefix #252

### PR DESCRIPTION
**Pull request by Yh010**

### CODE REVIEW

**Review by roopeshsn — COMMENTED** [review]
Hi, @Yh010! Your changes are, if the user input ends with '/' then it is considered a prefix, and appropriate options are loaded. Am I right?

**Comment by romain-fontugne** [comment]
thanks, for the changes but this is not going to work. An IP prefix looks like this: 192.168.0.0/16 or 10.0.0.0/8
The backslash is not the last character. There is always one or two characters after the /

**Comment by Yh010** [comment]
@romain-fontugne what if I change the condition to checking if the search query includes a forward slash . If it does then  a request will be sent to the api.

**Comment by roopeshsn** [comment]
Is there any possibility to use regex for a match @Yh010?

**Comment by Yh010** [comment]
@roopeshsn I suppose regex can match only a specific IP or a range of IP prefixes. this method would become very case specific right

**Comment by romain-fontugne** [comment]
Yes you can just check if there is a / in the search string. It is unlikely that AS names or country names will have that character

**Comment by Yh010** [comment]
Ok I'll do the changes

**Comment by Yh010** [comment]
Thanks @roopeshsn ...added the route code. By template do you mean the API code?

**Comment by roopeshsn** [comment]
> Thanks @roopeshsn ...added the route code. By template do you mean the API code?

No, I meant the code inside the template tag in the same file.

**Comment by roopeshsn** [comment]
> @romain-fontugne is the API end point for the hegemony_prefix API for fetching prefix data =  https://ihr.iijlab.net/ihr/api/prefixes  ??
> 
> I am confused about what end point I should add in the js file for representing the prefix data in a tabular format in a separate HTML file.
> @roopeshsn could you help me with this pls? I have made the commit for the HTML and Js file for your review

No, it should not be done like this. To render the prefix page, the code can be reused in 'Network.vue'.

But we have divided the parts that we are going to work at the start right? Right now, I am working on rendering the pages when the prefix is passed.

**Comment by Yh010** [comment]
> > @romain-fontugne is the API end point for the hegemony_prefix API for fetching prefix data =  https://ihr.iijlab.net/ihr/api/prefixes  ??
> > I am confused about what end point I should add in the js file for representing the prefix data in a tabular format in a separate HTML file.
> > @roopeshsn could you help me with this pls? I have made the commit for the HTML and Js file for your review
> 
> No, it should not be done like this. To render the prefix page, the code can be reused in 'Network.vue'.
> 
> But we have divided the parts that we are going to work at the start right? Right now, I am working on rendering the pages when the prefix is passed.

Ohk! Actually I thought fetching the data from API is also my part so I just created a rough HTML file so as to render the data on it, and left it for you to do further changes on it. Now that you'll do the rendering part, what do you want me to do now?

**Comment by Yh010** [comment]
> > Thanks @roopeshsn ...added the route code. By template do you mean the API code?
> 
> No, I meant the code inside the template tag in the same file.

done

**Comment by romain-fontugne** [comment]
Please be careful about what you are pushing. This PR is modifying/adding 9 different files and some changes seem completely irrelevant for the issue you are working on.

**Comment by romain-fontugne** [comment]
Any update on this?

**Comment by Yh010** [comment]
@romain-fontugne only the final rendering on the page is remaining...@roopeshsn if you are not able to find enough time then should I try to complete the remaining tasks so that we can close this issue?

**Comment by roopeshsn** [comment]
Hey, I am waiting for the search bar changes to be merged so that I can test with the rendering part. Looks like there are some conflicts to be resolved with this pr.

**Comment by Yh010** [comment]
Ok sure I'll resolve these quickly

**Comment by Yh010** [comment]
@roopeshsn pls check if it's still showing any conflict. i am not getting any option to resolve the conflicts now

**Comment by roopeshsn** [comment]
> @roopeshsn pls check if it's still showing any conflict. i am not getting any option to resolve the conflicts now

Yep, there are conflicts.

**Comment by roopeshsn** [comment]
Hey, here are my findings to remove the commits that were made by other developers and how to resolve conflicts in your branch.

1. Identify which commits are not your own:
- `git checkout <branch-name>`
- `git log`
-  Identify the commits that were made by other developers and note your commit IDs.

2. Create a new branch:
- `git checkout -b <new-branch-name> <upstream-branch-name>`
-  Cherry-pick only the commits that you made: `git cherry-pick <commit-ID-1> <commit-ID-2> ...`

3. Push the new branch and update the pull request:
- `git push origin <new-branch-name>`

4. Resolve any conflicts:
- `git checkout <new-branch-name>`
-  Merge the upstream branch into the new branch: `git merge <upstream-branch-name>`
-  Resolve any conflicts that arise during the merge.
-  Push the changes to the remote repository: `git push origin <new-branch-name>`

But the simple way is to create a new branch, copy paste your changes alone, commit, and raise a pull request. Hope this helps!

**Comment by romain-fontugne** [comment]
Yes, that's exactly why you should create a new branch when working on a new feature/bug. This is getting to messy, I'm closing this PR. Please open a new one using a new branch that contains only the changes you intend to make for this particular feature

**Comment by Yh010** [comment]
okay cool

**Comment by Yh010** [comment]
@romain-fontugne @roopeshsn  pls have a look : [PR](https://github.com/InternetHealthReport/ihr-website/pull/433)

**Comment by romain-fontugne** [comment]
@Yh010 did you see @roopeshsn 's comment in the PR?

**Pull request closed without merging**
