### PR TITLE
Italian Language Selector Added

### PR DESCRIPTION
**Pull request by MAVRICK-1**
Add Italian Language Translator

## Description

Translate the website into italian Language #664 

## Motivation and Context

make a multiLanguage Website

## Screenshots (if appropriate):

https://github.com/InternetHealthReport/ihr-website/assets/146999057/033202e4-5339-4b4a-b54e-acb37a4200d9

Screenshot 2023-12-19 112335

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the code style of this project.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@romain-fontugne  @mohamedawnallah  plz review my Pr

**Comment by dpgiakatos** [comment]
As I do not speak Italian, I am unable to review the content of this pull request. Consequently, I defer the review to other team members. It is essential to ensure that the translated content is free from any syntax, grammar, and vocabulary errors.

**Comment by romain-fontugne** [comment]
Sorry but this should first be discussed in the issue.

**Comment by MAVRICK-1** [comment]
> Sorry but this should first be discussed in the issue. 

Already discussed in #666 you said to go for it

**Comment by romain-fontugne** [comment]
well, this is neither french or german :)

**Comment by MAVRICK-1** [comment]
> well, this is neither french or german :)

Can I work on that?

**Comment by dpgiakatos** [comment]
I propose continuing the discussion for this after the merging of IYP pages because the translation file and some other files will change.

**Comment by MAVRICK-1** [comment]
> I propose continuing the discussion for this after the merging of IYP pages because the translation file and some other files will change.

That's sounds better

**Pull request closed without merging**
