### PR TITLE
Fix #423: internal link issues

### LINKED ISSUE #423: Global Report page's internal link incorrectly changes the URL
**Describe the bug**
This issue was brought up by https://github.com/InternetHealthReport/ihr-website/issues/382#issuecomment-1489781191.
I updated the description so that it's more accurate.
When we click the alarm buttons, the page will jump to the corresponding section. However, the URL of the page will be broken. The result is that when we copy and paste the link we'll be unable to see the site.

**To Reproduce**

> 1. Go to: https://ihr.iijlab.net/ihr/en-us/global_report
> 2. Click on any of the alarm buttons (example : Network Delay )
> 3. See the updated query
It should have been
//ihr.iijlab.net/ihr/en-us/global_report?[filter]#networkDelay
but, it is coming as //ihr.iijlab.net/#networkDelay

**Expected behavior**
The link should be correctly updated and remain functional after copy and paste.

**Screenshots**

Screenshot by https://github.com/InternetHealthReport/ihr-website/issues/382#issue-1645895334

### PR DESCRIPTION
**Pull request by Soohti**
## Description

Fix #423 

## Motivation and Context

The problem is that all pages of ihr-website has a base URL of "/" ([code](https://github.com/InternetHealthReport/ihr-website/blob/master/public/index.html#L50)), so we can't directly use fragment identifier. We should use the identifier together with the base URL for the resulting URL to be functional.

In this PR, 
* I changed the original ```<a href='...'>``` tags with ```<router-link>``` tags to point to the correct URL.
* I also removed four ```<a id='...'>``` tags that result in duplicated id.
* I updated the ```pushRoute()``` function so that the hash parameter will not be overrode on page load.

These duplicated-id tags have previously caused lint errors. When the page finished loading, the alarm buttons did not work. The buttons only worked when the page was still loading. So this caused a lot of confusion for me and others involved in #382 and made us can only reproduce the error with some luck.

By now, all the related issues should have been fixed.

## How Has This Been Tested?

I tested on my local computer. When I click an alarm button, the URL generated is correct.
I then copy the URL to another browser, the link also works.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Soohti** [comment]
The check failed because of the indentation error in https://github.com/InternetHealthReport/ihr-website/commit/2d523852db224ba36d6f519ba36ead82d5741e79.
I will fix it but it's not related to the issue.

**Comment by romain-fontugne** [comment]
The code looks good, but I cannot test it. Can you pull the latest version of master in your fork?

**Comment by romain-fontugne** [comment]
hmm somehow I cannot try your code (non-fast-forward error), but it is ok, I'll merge it and we can revert if it broke something

**Comment by romain-fontugne** [comment]
That's perfect, thanks!

**Pull request merged**
