### PR TITLE
118

### PR DESCRIPTION
**Pull request by thisiskaransgit**
## Description
Whenever the user will  request for a unspecified link they will be redirected to a custom 404 page 

## Motivation and Context

1. It helps the user to navigate through the site more efficiently
2. Will enhance the user experience

It fixes the issue #118 
## How Has This Been Tested?

1. It has been tested in the Local server
2. It has been tested with various with various URLs 
 >>For example 
 http://localhost:8080/ihr/en-us/documentation/search
 http://localhost:8080/ihr/en-us/documentation/search
 http://localhost:8080/ihr/en-us/api/s

## Screenshots (if appropriate):
1. Tablet view
tablet view
2. Mobile view
mobile view
4. Laptop view
laptop view

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Aniket762** [comment]
Hi, @thisiskaransgit thanks for the PR. It looks good to me, but as I said since the issue was primarily focused on UI, can you https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design for learning a bit more about the responsiveness.

PS. The CSS was not written using SCSS but it's fine

**Comment by Aniket762** [comment]
Hey @thisiskaransgit how are doing man? Are you working on this PR? If not that's fine let me know, so that I can decide accordingly :)

**Comment by thisiskaransgit** [comment]
> Hey @thisiskaransgit how are doing man? Are you working on this PR? If not that's fine let me know, so that I can decide accordingly :)

I am extremely sorry for the delay of the work , I was busy  as my Exams  started  due to which I was unable finish the PE  . But now I am free and  I'll be completing the work as soon as possible.

**Comment by Aniket762** [comment]
> > Hey @thisiskaransgit how are doing man? Are you working on this PR? If not that's fine let me know, so that I can decide accordingly :)
> 
> I am extremely sorry for the delay of the work , I was busy as my Exams started due to which I was unable finish the PE . But now I am free and I'll be completing the work as soon as possible.

Hey, nothing to be sorry about. It's open-source and you are contributing voluntarily. Take your time and work on it. Thank you, even after your exams are over you are willing to put in the hard work to fix your PR. We need more people like you as contributors 💖

**Comment by thisiskaransgit** [comment]
Hey @Aniket762 I am done with my work and have updated this pull request. 

**Update :** 
1. Feature added : responsive page  
2. Added stylus language  for CSS
3. Changed the page design to make it responsive 
4.  Removed the 404 image as it was not needed now 


The custom page is working as we needed 
1. Mobile View 
Screenshot 2022-05-19 210624

4. Tablet view
Screenshot 2022-05-19 210657

6. Laptop view 
Screenshot 2022-05-19 210558

**Comment by thisiskaransgit** [comment]
Hey @Aniket762 Hope you are doing well,  Just wanted  to ask you for a review on the PR

**Pull request merged**
