### PR TITLE
Feat: Added New & updated the existing GitHub actions 

### PR DESCRIPTION
**Pull request by thisiskaransgit**
## Description
Fixes PR for #286 

Merge this and #315 simultaneously

### Added GitHub Actions
1. Eslint
2. Performance checker

### Resolved the issues in 
1. CodeQl action
2. Greetings action

### 3. Update Dependabot action: 

as mentioned in the conversation 

> The dependant bot, should be configured more precisely so that it does not bump dependency to a major version (which may introduce breaking changes)

- to ignore any major version bumps to avoid breaking changes
- to update the package and lockfile together 

>  and also create, test, merge and close the PR by itself.

This will require a new workflow and will be added with another PR.

## Motivation and Context
Have added the above-mentioned actions to check the incoming PRs to maintain the code quality and catch any overlooked issue

## How Has This Been Tested?

Has been tested in the Forked Repo.

Screenshot from 2023-03-08 23-28-18

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by thisiskaransgit** [comment]
The lint is failing since it expects the lockfile in the repo, after the `package-lock.json` is committed it will work fine.

**Comment by aabhas-sao** [comment]
> The lint is failing since it expects the lockfile in the repo, after the `package-lock.json` is committed it will work fine.

Yeah that seems like good idea and it is also recommended. Below is quote from official npm site about [package-locks](https://docs.npmjs.com/cli/v6/configuring-npm/package-locks).
>It is highly recommended you commit the generated package lock to source control: this will allow anyone else on your team, your deployments, your CI/continuous integration, and anyone else who runs npm install in your package source to get the exact same dependency tree that you were developing on. Additionally, the diffs from these changes are human-readable and will inform you of any changes npm has made to your node_modules, so you can notice if any transitive dependencies were updated, hoisted, etc.

**Comment by romain-fontugne** [comment]
I still see the lint failing but anyways let's merge this one and see if we have to fix things after :D

**Comment by romain-fontugne** [comment]
ok, thanks

**Pull request merged**
