### PR TITLE
Fixes issue 847: Fixed the glitch

### PR DESCRIPTION
**Pull request by abansal15**
## Description
Fixed the glitch while loading 

## Screenshots (if appropriate):

https://github.com/user-attachments/assets/b175394c-6336-4a05-99ca-ca401a12f42d

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dpgiakatos** [comment]
Hello, thank you for your pull request. Before we proceed with the code review, please take a moment to read our contribution guidelines. It appears that you have made changes to the `master` branch, which is our release branch. We use the `dev` branch for development, as it contains our latest code. Additionally, I noticed that your IP address is exposed in the video linked in this PR. Please take care to address this. Thank you!

**Comment by abansal15** [comment]
> Hello, thank you for your pull request. Before we proceed with the code review, please take a moment to read our contribution guidelines. It appears that you have made changes to the `master` branch, which is our release branch. We use the `dev` branch for development, as it contains our latest code. Additionally, I noticed that your IP address is exposed in the video linked in this PR. Please take care to address this. Thank you!

Yes sure sir now from onwards I will raise the pr to the development branch and take care of the ip
Thanks a lot and soory for the mistake I will not repeat it again

**Comment by dpgiakatos** [comment]
You can find our latest contribution guidelines at the following link:
https://github.com/InternetHealthReport/ihr-website/blob/dev/CONTRIBUTING.md

Thanks!

**Comment by abansal15** [comment]
Sure @dpgiakatos i follow this and don't repeat the mistake in the future

**Comment by dpgiakatos** [comment]
Hello,

This pull request (PR) proposes changes across 214 files, with a total of 30,600 lines added and 21,286 lines removed. As a result, I will be closing this PR. I recommend reopening it after reviewing our latest contribution guidelines, which can be found at the following link:  
https://github.com/InternetHealthReport/ihr-website/blob/dev/CONTRIBUTING.md

To assist you in the process, please follow these steps:

1. Fork and clone the project
2. Switch to the `dev` branch
3. Make your code changes in that branch (`dev` branch)
4. Sync with the latest changes in the `dev` branch (if any)
5. Create a new PR targeting the `dev` branch

Thank you!

**Comment by abansal15** [comment]
> Hello,
> 
> This pull request (PR) proposes changes across 214 files, with a total of 30,600 lines added and 21,286 lines removed. As a result, I will be closing this PR. I recommend reopening it after reviewing our latest contribution guidelines, which can be found at the following link: https://github.com/InternetHealthReport/ihr-website/blob/dev/CONTRIBUTING.md
> 
> To assist you in the process, please follow these steps:
> 
> 1. Fork and clone the project
> 2. Switch to the `dev` branch
> 3. Make your code changes in that branch (`dev` branch)
> 4. Sync with the latest changes in the `dev` branch (if any)
> 5. Create a new PR targeting the `dev` branch
> 
> Thank you!

sir according to the contribution guideline should i have to do code chnages in the dev branch or shouls make a new branch with that issue number ?
image

**Pull request closed without merging**
