### PR TITLE
User mngt

### PR DESCRIPTION
**Pull request by mhmdahmedfathi**
## Description

1. Changes in router.js by adding a new route "login," which will redirect the user to the login page, and fixing the signup route by making its component the register component, not the signup component (which I request be changed to signin because if you look inside the signup page, you will see it is the login, so this page name is misleading). 

2. fix networks.vue by adding "," as it was missing and this fact will give an error
3. fix errors in resetpassword and signup by commented the uncommented tags as you will find some tags like "  </div> -->"

## Motivation and Context

In the user mngt branch, if you tried to click register button that is found in the home page it will redirect to the login page and the login button will redirect you to nowhere 

the errors in networks " adding comma" , reset password and signup "comment half commented tags" will give syntax error so it won't make the app run

## How Has This Been Tested?

you can simply try it 

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Aniket762** [comment]
Hey @mhmdahmedfathi , can you please mention the issue number for which you have sent the PR? Also, it's better if you can give mention some ways you have tested rather than `you can simply try it`. 

Would be really helpful, if you can follow the Contributing Guidelines before sending in the PRs. Closing the PR as of now.

**Comment by mhmdahmedfathi** [comment]
Hey @Aniket762 , I'm very sorry about that; I don't mean anything by it; it is just a syntax error, so I don't know exactly how I can write the script to test it. What I mean is that I simply run the code and it gives me this error, and it isn't related to any issue because what happened was that @romain-fontugne told me to test the user-management flow to see if there were any issues, and when there were, I fixed them and pushed a PR with it. So I'm sorry again.
And if I may ask, what can I do now?

**Comment by Aniket762** [comment]
> Hey @Aniket762 , I'm very sorry about that; I don't mean anything by it; it is just a syntax error, so I don't know exactly how I can write the script to test it. What I mean is that I simply run the code and it gives me this error, and it isn't related to any issue because what happened was that @romain-fontugne told me to test the user-management flow to see if there were any issues, and when there were, I fixed them and pushed a PR with it. So I'm sorry again. And if I may ask, what can I do now?

Had no idea that Romain told you to work on it. Reopen the issue, will be waiting for @romain-fontugne to review it. But, please follow the contributing guidelines from the next time.

**Comment by romain-fontugne** [comment]
To comply to our guidelines, let's open an issue for this :)

**Comment by romain-fontugne** [comment]
looks good, @Aniket762 is right, next time let's open an issue first!

**Comment by mhmdahmedfathi** [comment]
@Aniket762  @romain-fontugne First and foremost, thank you both; for the guidelines, I have added some screenshots and attempted to be more clear; and I am confident that the next time I will try to avoid this.

**Pull request merged**
